[build]
  base = "."
  publish = "dist"
  command = "npm run build"

[context.production]
  environment = { NODE_ENV = "production", VITE_API_URL = "https://beifi-smart-city-dashboard-1.onrender.com" }

[context.deploy-preview]
  environment = { NODE_ENV = "development", VITE_API_URL = "https://beifi-smart-city-dashboard-1.onrender.com" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
