[build]
  base = "frontend"
  publish = "dist"
  command = "npm install --include=dev && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://i-dashboard-api.onrender.com"
